import { View, Text, Link } from '@react-pdf/renderer';
import { styles } from '../styles';

interface FooterProps {
  characterId?: string | null;
}

export function Footer({ characterId }: FooterProps) {
  const shareUrl = characterId
    ? `https://cat-stats-six.vercel.app/legend/${characterId}`
    : null;

  return (
    <View style={styles.footer}>
      {shareUrl && (
        <Link src={shareUrl} style={styles.footerLink}>
          View online: {shareUrl}
        </Link>
      )}
      <Text style={styles.footerText}>
        Generated by CatStats - Turn your pet into a legend!
      </Text>
    </View>
  );
}
