import { pdf } from '@react-pdf/renderer';
import type { CharacterSheet } from '../core/personality/types';
import { CharacterSheetPDF } from '../components/PDF';

export function generateTextExport(characterSheet: CharacterSheet): void {
  const { characterData, stats, petName } = characterSheet;

  const textContent = `
╔═══════════════════════════════════════════════════════════════╗
║                           CATSTATS                            ║
║                    FELINE LEGEND CHARACTER SHEET             ║
╠═══════════════════════════════════════════════════════════════╣

🐱 NAME: ${petName.toUpperCase()}
🏆 ARCHETYPE: ${characterData.archetype}

╔═══════════════════════════════════════════════════════════════╗
║                        CORE ATTRIBUTES                       ║
╠═══════════════════════════════════════════════════════════════╣
║ Wisdom...................................... ${stats.wisdom.toString().padStart(3)} ║
║ Cunning..................................... ${stats.cunning.toString().padStart(3)} ║
║ Agility..................................... ${stats.agility.toString().padStart(3)} ║
║ Stealth..................................... ${stats.stealth.toString().padStart(3)} ║
║ Charisma.................................... ${stats.charisma.toString().padStart(3)} ║
║ Resolve..................................... ${stats.resolve.toString().padStart(3)} ║
╚═══════════════════════════════════════════════════════════════╝

⚔️  COMBAT MOVES:
${characterData.combatMoves
  .map(
    (ability) =>
      `• ${ability.name}\n  ${ability.stats}\n  ${ability.description}\n`
  )
  .join('')}

🌍 ENVIRONMENTAL POWERS:
${characterData.environmentalPowers
  .map(
    (ability) =>
      `• ${ability.name}\n  ${ability.stats}\n  ${ability.description}\n`
  )
  .join('')}

💬 SOCIAL SKILLS:
${characterData.socialSkills
  .map(
    (ability) =>
      `• ${ability.name}\n  ${ability.stats}\n  ${ability.description}\n`
  )
  .join('')}

🔮 PASSIVE TRAITS:
${characterData.passiveTraits
  .map(
    (ability) =>
      `• ${ability.name}\n  ${ability.stats}\n  ${ability.description}\n`
  )
  .join('')}

⚠️  CRITICAL VULNERABILITY:
• ${characterData.weakness.name}
  ${characterData.weakness.description}

🕒 SITUATIONAL MODIFIERS:
${characterData.timeModifiers
  .map((modifier) => `• ${modifier.name}: ${modifier.effect}\n`)
  .join('')}

╔═══════════════════════════════════════════════════════════════╗
║                    Generated by CatStats                     ║
║                  Turn your pet into a legend!                ║
╚═══════════════════════════════════════════════════════════════╝
`;

  // Create and download as a text file
  const blob = new Blob([textContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${petName}-CatStats-Legend.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  alert(
    `✨ ${petName}'s character sheet downloaded! Perfect for printing or sharing.`
  );
}

export async function generatePdfExport(
  characterSheet: CharacterSheet,
  characterId?: string | null
): Promise<void> {
  const { petName } = characterSheet;

  // Generate PDF blob using React-PDF
  const blob = await pdf(
    <CharacterSheetPDF
      characterSheet={characterSheet}
      characterId={characterId}
    />
  ).toBlob();

  // Download the PDF
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${petName}-CatStats-Legend.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
