name: Database Heartbeat

# Run every 6 hours to keep the database active
on:
  schedule:
    # Runs at 00:00, 06:00, 12:00, 18:00 UTC every day
    - cron: '0 */6 * * *'

  # Allow manual trigger from GitHub Actions UI
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run heartbeat
        env:
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
        run: node tools/heartbeat.js

      - name: Keep repo active (prevent workflow auto-disable)
        if: github.event.schedule # Only on scheduled runs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Last heartbeat: $(date)" > .github/last-heartbeat.txt
          git add .github/last-heartbeat.txt || true
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update heartbeat timestamp [skip ci]" && git push)
